import type { Framework, AgentMode } from "../types.js";

interface ApiWrapperConfig {
  projectName: string;
  framework: Framework;
  agentMode: AgentMode;
  agentNames?: string[];
  port: number;
}

function getFrameworkImport(framework: Framework, agentMode: AgentMode): string {
  if (agentMode === "multi") {
    return `from src.pipeline import run_pipeline`;
  }
  return `from src.agents.agent import run_agent`;
}

function getInvokeCall(framework: Framework, agentMode: AgentMode): string {
  if (agentMode === "multi") {
    return `run_pipeline(request.prompt)`;
  }
  return `run_agent(request.prompt)`;
}

function getResultExtract(agentMode: AgentMode): string {
  if (agentMode === "multi") {
    return `        response = str(result["result"]) if isinstance(result, dict) else str(result)
        guard_summary = result.get("guard_summary") if isinstance(result, dict) else None`;
  }
  return `        response = str(result)
        guard_summary = None`;
}

export function generateServerPy(config: ApiWrapperConfig): string {
  const { projectName, framework, agentMode, port } = config;
  const frameworkImport = getFrameworkImport(framework, agentMode);
  const invokeCall = getInvokeCall(framework, agentMode);
  const resultExtract = getResultExtract(agentMode);

  return `"""
API server — Generated by AgentVoy
Wraps your agent as a FastAPI endpoint with agent.guard.yml enforcement.

Run:
    uvicorn server:app --reload --port ${port}

Endpoints:
    POST /run    — send a prompt, get a response
    GET  /health — health check
"""
import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

${frameworkImport}

app = FastAPI(
    title="${projectName}",
    description="AI agent powered by AgentVoy",
    version="0.1.0",
)


class AgentRequest(BaseModel):
    prompt: str
    session_id: str | None = None


class AgentResponse(BaseModel):
    response: str
    guard_summary: dict | None = None


@app.post("/run")
async def run(request: AgentRequest) -> AgentResponse:
    try:
        result = ${invokeCall}
${resultExtract}
        return AgentResponse(response=response, guard_summary=guard_summary)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/health")
async def health():
    return {"status": "ok", "agent": "${projectName}"}


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=${port})
`;
}
