import type { DeploymentAdapter, DeployConfig, DeploymentFiles, DeployValidationResult } from "../types.js";
import { mapGuardToCloudConfig } from "./guard-mapper.js";

function generateSamTemplate(config: DeployConfig): string {
  const { projectName, port } = config;
  const cloudConfig = mapGuardToCloudConfig(config.guard);
  const timeoutSeconds = cloudConfig.timeout
    ? parseInt(cloudConfig.timeout.replace("s", ""), 10)
    : 300;
  const memoryMb = cloudConfig.memory?.includes("Gi")
    ? parseInt(cloudConfig.memory) * 1024
    : 512;

  return `# template.yaml — AWS SAM template — Generated by AgentVoy
# Deploy: sam build && sam deploy --guided

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Description: ${projectName} — AI agent deployed with AgentVoy

Globals:
  Function:
    Timeout: ${timeoutSeconds}
    MemorySize: ${memoryMb}
    Environment:
      Variables:
        PORT: "${port}"

Resources:
  AgentFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ${projectName.toLowerCase().replace(/[^a-z0-9-]/g, "-")}
      PackageType: Image
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://\${ServerlessHttpApi}.execute-api.\${AWS::Region}.amazonaws.com/"
`;
}

function generateMangumPatch(): string {
  return `"""
AWS Lambda handler — add to server.py or as a separate handler.py
Uses Mangum to wrap the FastAPI app for Lambda.
"""
from mangum import Mangum
from server import app  # import your FastAPI app

# Lambda handler
handler = Mangum(app, lifespan="off")
`;
}

export const awsLambdaAdapter: DeploymentAdapter = {
  target: "aws-lambda",
  displayName: "AWS Lambda",
  requiredCLI: "sam",

  async validate(config: DeployConfig): Promise<DeployValidationResult> {
    const errors: { field: string; message: string }[] = [];
    const warnings: { field: string; message: string }[] = [];
    const missingTools: string[] = [];

    try {
      const { execSync } = await import("child_process");
      execSync("sam --version", { stdio: "ignore" });
    } catch {
      missingTools.push("sam");
      warnings.push({
        field: "sam",
        message: "AWS SAM CLI not found — install from https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html",
      });
    }

    return { valid: errors.length === 0, errors, warnings, missingTools };
  },

  async generateFiles(config: DeployConfig): Promise<DeploymentFiles> {
    const files = [
      { path: "deploy/template.yaml", content: generateSamTemplate(config) },
      { path: "deploy/lambda_handler.py", content: generateMangumPatch() },
    ];

    const instructions = [
      `pip install mangum  # Lambda adapter for FastAPI`,
      `aws configure  # set AWS credentials`,
      `sam build`,
      `sam deploy --guided`,
      `# Follow prompts to set stack name, region, and env vars`,
    ];

    return { files, instructions };
  },
};
