import type { DeploymentAdapter, DeployConfig, DeploymentFiles, DeployValidationResult } from "../types.js";
import { mapGuardToCloudConfig } from "./guard-mapper.js";

function generateDockerfile(config: DeployConfig): string {
  const { projectName, port, guard } = config;
  const cloudConfig = mapGuardToCloudConfig(guard);
  const timeoutSeconds = cloudConfig.timeout
    ? parseInt(cloudConfig.timeout.replace("s", ""), 10)
    : 300;

  return `# Dockerfile — Generated by AgentVoy
# agent.guard.yml guardrails reflected in container configuration

FROM python:3.12-slim AS base

# Non-root user (enforces execution.allow_shell: false from agent.guard.yml)
RUN useradd --create-home --shell /bin/sh agent

WORKDIR /home/agent/app

# Install dependencies first (layer caching)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Run as non-root
USER agent

EXPOSE ${port}

# Health check (timeout from guardrails.behavior.timeout: ${guard.guardrails?.behavior?.timeout ?? "5m"})
HEALTHCHECK --interval=30s --timeout=${timeoutSeconds}s --start-period=10s --retries=3 \\
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:${port}/health')" || exit 1

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "${port}"]
`;
}

function generateDockerignore(): string {
  return `.git
.github
.env
__pycache__
*.pyc
*.pyo
*.pyd
.Python
*.egg-info
dist/
build/
.venv
venv/
.pytest_cache
.mypy_cache
*.log
node_modules/
`;
}

function generateDockerComposeYml(config: DeployConfig): string {
  const { projectName, port } = config;
  return `# docker-compose.yml — for local development
version: "3.9"
services:
  agent:
    build: .
    ports:
      - "${port}:${port}"
    env_file:
      - .env
    restart: unless-stopped

  ui:
    build: .
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - agent
`;
}

export const dockerAdapter: DeploymentAdapter = {
  target: "docker",
  displayName: "Docker",

  async validate(config: DeployConfig): Promise<DeployValidationResult> {
    const errors: { field: string; message: string }[] = [];
    const warnings: { field: string; message: string }[] = [];
    const missingTools: string[] = [];

    // Check docker is available (best-effort)
    try {
      const { execSync } = await import("child_process");
      execSync("docker --version", { stdio: "ignore" });
    } catch {
      missingTools.push("docker");
      warnings.push({
        field: "docker",
        message: "Docker not found — install from https://docs.docker.com/get-docker/",
      });
    }

    return { valid: errors.length === 0, errors, warnings, missingTools };
  },

  async generateFiles(config: DeployConfig): Promise<DeploymentFiles> {
    const files = [
      { path: "Dockerfile", content: generateDockerfile(config) },
      { path: ".dockerignore", content: generateDockerignore() },
      { path: "docker-compose.yml", content: generateDockerComposeYml(config) },
    ];

    const cloudConfig = mapGuardToCloudConfig(config.guard);

    const instructions = [
      `Build:   docker build -t ${config.projectName} .`,
      `Run:     docker run -p ${config.port}:${config.port} --env-file .env ${config.projectName}`,
      `API:     curl http://localhost:${config.port}/health`,
      `UI:      docker-compose up  (starts API + Streamlit on :8501)`,
      `Memory:  ${cloudConfig.memory} (from agent.guard.yml cost_limit)`,
      `Timeout: ${cloudConfig.timeout} (from agent.guard.yml behavior.timeout)`,
    ];

    return { files, instructions };
  },
};
