import type { DeploymentAdapter, DeployConfig, DeploymentFiles, DeployValidationResult } from "../types.js";
import { mapGuardToCloudConfig } from "./guard-mapper.js";

function generateFlyToml(config: DeployConfig): string {
  const { projectName, port } = config;
  const cloudConfig = mapGuardToCloudConfig(config.guard);
  const timeoutSeconds = cloudConfig.timeout
    ? parseInt(cloudConfig.timeout.replace("s", ""), 10)
    : 300;

  return `# fly.toml — Generated by AgentVoy
# Deploy: fly launch (first time) or fly deploy

app = "${projectName.toLowerCase().replace(/[^a-z0-9-]/g, "-")}"
primary_region = "${config.cloudConfig?.region ?? "iad"}"

[build]

[http_service]
  internal_port = ${port}
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = "${cloudConfig.memory ?? "512mb"}"
  cpu_kind = "shared"
  cpus = 1

[processes]
  app = "uvicorn server:app --host 0.0.0.0 --port ${port}"

[env]
  PORT = "${port}"

# kill_timeout from guardrails.behavior.timeout
kill_timeout = ${timeoutSeconds}
`;
}

export const flyIoAdapter: DeploymentAdapter = {
  target: "fly-io",
  displayName: "Fly.io",
  requiredCLI: "flyctl",

  async validate(config: DeployConfig): Promise<DeployValidationResult> {
    const errors: { field: string; message: string }[] = [];
    const warnings: { field: string; message: string }[] = [];
    const missingTools: string[] = [];

    try {
      const { execSync } = await import("child_process");
      execSync("flyctl version", { stdio: "ignore" });
    } catch {
      missingTools.push("flyctl");
      warnings.push({
        field: "flyctl",
        message: "flyctl not found — install from https://fly.io/docs/hands-on/install-flyctl/",
      });
    }

    return { valid: errors.length === 0, errors, warnings, missingTools };
  },

  async generateFiles(config: DeployConfig): Promise<DeploymentFiles> {
    const files = [
      { path: "deploy/fly.toml", content: generateFlyToml(config) },
    ];

    const appName = config.projectName.toLowerCase().replace(/[^a-z0-9-]/g, "-");
    const instructions = [
      `Install flyctl: https://fly.io/docs/hands-on/install-flyctl/`,
      `fly auth login`,
      `fly launch --name ${appName} --copy-config`,
      `fly secrets set OPENAI_API_KEY=<your-key>  # set all required env vars`,
      `fly deploy`,
      `fly open  # open in browser`,
    ];

    return { files, instructions };
  },
};
