import type { DeploymentAdapter, DeployConfig, DeploymentFiles, DeployValidationResult } from "../types.js";
import { mapGuardToCloudConfig } from "./guard-mapper.js";

function generateCloudRunYaml(config: DeployConfig): string {
  const { projectName, port } = config;
  const cloudConfig = mapGuardToCloudConfig(config.guard);
  const region = config.cloudConfig?.region ?? "us-central1";

  return `# cloud-run.yaml — Generated by AgentVoy
# Deploy: gcloud run deploy ${projectName} --source . --region ${region}

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${projectName.toLowerCase()}
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      timeoutSeconds: ${cloudConfig.timeout ? parseInt(cloudConfig.timeout, 10) : 300}
      containers:
        - image: gcr.io/PROJECT_ID/${projectName.toLowerCase()}
          ports:
            - containerPort: ${port}
          resources:
            limits:
              memory: ${cloudConfig.memory ?? "512Mi"}
              cpu: "1"
          env:
            - name: PORT
              value: "${port}"
`;
}

export const gcpCloudRunAdapter: DeploymentAdapter = {
  target: "gcp-cloud-run",
  displayName: "GCP Cloud Run",
  requiredCLI: "gcloud",

  async validate(config: DeployConfig): Promise<DeployValidationResult> {
    const errors: { field: string; message: string }[] = [];
    const warnings: { field: string; message: string }[] = [];
    const missingTools: string[] = [];

    try {
      const { execSync } = await import("child_process");
      execSync("gcloud --version", { stdio: "ignore" });
    } catch {
      missingTools.push("gcloud");
      warnings.push({
        field: "gcloud",
        message: "gcloud CLI not found — install from https://cloud.google.com/sdk/docs/install",
      });
    }

    return { valid: errors.length === 0, errors, warnings, missingTools };
  },

  async generateFiles(config: DeployConfig): Promise<DeploymentFiles> {
    const region = config.cloudConfig?.region ?? "us-central1";
    const name = config.projectName.toLowerCase();

    const files = [
      { path: "deploy/cloud-run.yaml", content: generateCloudRunYaml(config) },
    ];

    const instructions = [
      `gcloud auth login`,
      `gcloud config set project YOUR_PROJECT_ID`,
      `gcloud run deploy ${name} --source . --region ${region} --allow-unauthenticated`,
      `# Or using the YAML: gcloud run services replace deploy/cloud-run.yaml`,
    ];

    return { files, instructions };
  },
};
