import type { Framework } from "../types.js";

interface PipelineConfig {
  projectName: string;
  framework: Framework;
  agentNames: string[];
}

export function generatePipelinePy(config: PipelineConfig): string {
  const { agentNames } = config;

  const imports = agentNames
    .map((name) => `from src.agents.${name} import run_agent as ${name}_agent`)
    .join("\n");

  const stages = agentNames
    .map((name, i) => {
      const inputVar = i === 0 ? "prompt" : `${agentNames[i - 1]}_result`;
      return `        # Stage ${i + 1}: ${name}
        ${name}_result = ${name}_agent(${inputVar})
        session.tick()`;
    })
    .join("\n\n");

  const finalVar = `${agentNames[agentNames.length - 1]}_result`;
  const stagesList = agentNames.map((n) => `"${n}"`).join(", ");

  return `"""
Multi-agent pipeline — Generated by AgentVoy
Agents run sequentially, each building on the previous stage's output.

Stages: ${agentNames.join(" → ")}
"""
from agentvoy_guard import Guard

${imports}

guard = Guard.from_config()


def run_pipeline(prompt: str) -> dict:
    """Run all agents in sequence and return the final result."""
    with guard.session() as session:
        session.check_input(prompt)

${stages}

        session.check_output(str(${finalVar}))

    return {
        "result": ${finalVar},
        "stages": [${stagesList}],
        "guard_summary": guard.last_summary,
    }


if __name__ == "__main__":
    import sys
    user_prompt = " ".join(sys.argv[1:]) or "Hello! What can you help me with?"
    result = run_pipeline(user_prompt)
    print(result["result"])
`;
}
