import type { AgentMode } from "../types.js";

interface StreamlitConfig {
  projectName: string;
  agentMode: AgentMode;
  agentNames?: string[];
  port: number;
}

export function generateStreamlitApp(config: StreamlitConfig): string {
  const { projectName, agentMode, agentNames, port } = config;

  const pipelineSteps =
    agentMode === "multi" && agentNames && agentNames.length > 0
      ? agentNames.map((n) => `"${n}"`).join(", ")
      : "";

  const pipelineSection =
    agentMode === "multi"
      ? `
                if data.get("stages"):
                    with st.expander("Pipeline stages", expanded=False):
                        for stage in data["stages"]:
                            st.write(f"\\u2713 {stage}")
`
      : "";

  return `"""
Chat UI — Generated by AgentVoy
Streamlit app that talks to the FastAPI server.

Run (with server already running on port ${port}):
    streamlit run streamlit_app.py
"""
import streamlit as st
import requests

API_URL = "http://localhost:${port}"

st.set_page_config(
    page_title="${projectName}",
    page_icon="🤖",
    layout="centered",
)
st.title("${projectName}")
st.caption("Powered by AgentVoy")

${agentMode === "multi" && pipelineSteps ? `with st.sidebar:\n    st.subheader("Pipeline")\n    for stage in [${pipelineSteps}]:\n        st.write(f"• {stage}")` : ""}

if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])

if prompt := st.chat_input("Ask your agent..."):
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.write(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            try:
                resp = requests.post(
                    f"{API_URL}/run",
                    json={"prompt": prompt},
                    timeout=120,
                )
                resp.raise_for_status()
                data = resp.json()
                st.write(data["response"])
${pipelineSection}
                if data.get("guard_summary"):
                    with st.sidebar:
                        st.subheader("Guard summary")
                        st.json(data["guard_summary"])

            except requests.exceptions.ConnectionError:
                st.error(f"Cannot connect to agent server at {API_URL}. Is it running?")
                st.code(f"uvicorn server:app --port ${port}")
                data = {"response": ""}
            except Exception as e:
                st.error(f"Error: {e}")
                data = {"response": ""}

    if data.get("response"):
        st.session_state.messages.append({"role": "assistant", "content": data["response"]})
`;
}
