/**
 * Tracer module generator
 *
 * Generates src/trace/tracer.py for app-mode projects.
 * The tracer collects agent execution events and exposes them
 * via WebSocket for the DevTools dashboard.
 */

export function generateTracerPy(): string {
  return `"""
Agent Tracer — Generated by AgentVoy
Collects execution events and streams them to the DevTools dashboard.
"""

import time
import uuid
import json
import asyncio
from dataclasses import dataclass, field, asdict
from typing import Any


@dataclass
class TraceEvent:
    """A single trace event."""
    type: str
    timestamp: float
    data: dict = field(default_factory=dict)
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])


class Tracer:
    """Singleton tracer that collects agent execution events."""
    _instance: "Tracer | None" = None

    def __init__(self):
        self.events: list[TraceEvent] = []
        self.listeners: list[asyncio.Queue] = []
        self.session_id: str = ""
        self.start_time: float = 0
        self.total_cost: float = 0
        self.total_tokens_in: int = 0
        self.total_tokens_out: int = 0

    @classmethod
    def get(cls) -> "Tracer":
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def new_session(self) -> str:
        """Start a new trace session."""
        self.events = []
        self.start_time = time.time()
        self.total_cost = 0
        self.total_tokens_in = 0
        self.total_tokens_out = 0
        self.session_id = uuid.uuid4().hex[:8]
        return self.session_id

    def emit(self, event_type: str, **data: Any) -> TraceEvent:
        """Emit a trace event."""
        event = TraceEvent(type=event_type, timestamp=time.time(), data=data)
        self.events.append(event)
        # Notify WebSocket listeners
        for queue in list(self.listeners):
            try:
                queue.put_nowait(event)
            except Exception:
                pass
        return event

    def agent_start(self, agent_name: str, prompt: str, model: str = ""):
        """Emit when an agent starts processing."""
        self.new_session()
        self.emit("agent_start", agent=agent_name, prompt=prompt, model=model)

    def llm_call(self, model: str, tokens_in: int = 0, tokens_out: int = 0,
                 cost: float = 0, latency: float = 0, prompt_preview: str = "",
                 response_preview: str = ""):
        """Emit after an LLM API call."""
        self.total_tokens_in += tokens_in
        self.total_tokens_out += tokens_out
        self.total_cost += cost
        self.emit("llm_call", model=model, tokens_in=tokens_in,
                  tokens_out=tokens_out, cost=cost, latency=latency,
                  prompt_preview=prompt_preview[:200],
                  response_preview=response_preview[:500])

    def tool_call(self, tool_name: str, tool_input: str = "", tool_output: str = "",
                  latency: float = 0):
        """Emit when a tool is called."""
        self.emit("tool_call", tool=tool_name, input=tool_input[:200],
                  output=tool_output[:500], latency=latency)

    def guard_check(self, check_type: str, passed: bool, details: str = ""):
        """Emit when a guardrail check runs."""
        self.emit("guard_check", check_type=check_type, passed=passed, details=details)

    def pipeline_stage(self, stage_name: str, stage_index: int, total_stages: int,
                       status: str = "running"):
        """Emit pipeline stage transition."""
        self.emit("pipeline_stage", stage=stage_name, index=stage_index,
                  total=total_stages, status=status)

    def agent_complete(self, agent_name: str, result_preview: str = "",
                       total_latency: float = 0):
        """Emit when agent finishes."""
        if total_latency == 0 and self.start_time:
            total_latency = time.time() - self.start_time
        self.emit("agent_complete", agent=agent_name,
                  result_preview=result_preview[:500],
                  total_latency=round(total_latency, 2),
                  total_cost=round(self.total_cost, 6),
                  total_tokens_in=self.total_tokens_in,
                  total_tokens_out=self.total_tokens_out)

    def error(self, message: str, agent_name: str = ""):
        """Emit an error event."""
        self.emit("error", message=message, agent=agent_name)

    def subscribe(self) -> asyncio.Queue:
        """Subscribe to real-time events via a queue."""
        queue: asyncio.Queue = asyncio.Queue()
        self.listeners.append(queue)
        return queue

    def unsubscribe(self, queue: asyncio.Queue):
        """Remove a listener."""
        if queue in self.listeners:
            self.listeners.remove(queue)

    def get_events_json(self) -> list[dict]:
        """Return all events as JSON-serializable dicts."""
        return [asdict(e) for e in self.events]

    def get_summary(self) -> dict:
        """Return session summary."""
        return {
            "session_id": self.session_id,
            "event_count": len(self.events),
            "total_cost": round(self.total_cost, 6),
            "total_tokens_in": self.total_tokens_in,
            "total_tokens_out": self.total_tokens_out,
            "elapsed": round(time.time() - self.start_time, 2) if self.start_time else 0,
        }


# Convenience: module-level singleton
tracer = Tracer.get()
`;
}
