/**
 * Shared helpers for app-mode scaffolding.
 * Used by all framework adapters when buildMode="app".
 */

import type { ScaffoldConfig, GeneratedFile } from "../types.js";

/** Common infrastructure files for the src/ app structure */
export function generateAppInfraFiles(config: ScaffoldConfig): GeneratedFile[] {
  return [
    { path: "src/__init__.py", content: "" },
    { path: "src/agents/__init__.py", content: "" },
    { path: "src/tools/__init__.py", content: "" },
    { path: "src/config/__init__.py", content: "" },
    {
      path: "src/config/settings.py",
      content: `"""App settings — Generated by AgentVoy"""
import os

PORT = int(os.getenv("PORT", "8080"))
DEBUG = os.getenv("DEBUG", "false").lower() == "true"
AGENT_NAME = "${config.projectName}"
`,
    },
  ];
}

/** Append app deployment dependencies to a requirements string */
export function appendAppRequirements(base: string): string {
  const appDeps = [
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.34.0",
    "streamlit>=1.40.0",
    "requests>=2.32.0",
  ];
  return base.trimEnd() + "\n" + appDeps.join("\n") + "\n";
}

/** Post-install instructions for app mode */
export function appPostInstallInstructions(envVar: string): string[] {
  return [
    "pip install -r requirements.txt",
    "cp .env.example .env",
    `Add your ${envVar} to .env`,
    "uvicorn server:app --reload --port 8080",
    "streamlit run streamlit_app.py  # in a second terminal",
  ];
}
